/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : string,
  'eventId' : bigint,
  'bookedAt' : bigint,
  'userId' : Principal,
  'quantity' : bigint,
}
export interface Event {
  'id' : bigint,
  'venue' : string,
  'name' : string,
  'description' : string,
  'totalSeats' : bigint,
  'imageUrl' : string,
  'bookedSeats' : bigint,
  'isFeatured' : boolean,
  'category' : string,
  'price' : number,
  'dateTime' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookTickets' : ActorMethod<[bigint, bigint], bigint>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createEvent' : ActorMethod<[Event], bigint>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEventById' : ActorMethod<[bigint], Event>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markEventAsFeatured' : ActorMethod<[bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];