/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'venue' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'totalSeats' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'bookedSeats' : IDL.Nat,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'dateTime' : IDL.Int,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'eventId' : IDL.Nat,
  'bookedAt' : IDL.Int,
  'userId' : IDL.Principal,
  'quantity' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookTickets' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createEvent' : IDL.Func([Event], [IDL.Nat], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEventById' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markEventAsFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'venue' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'totalSeats' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'bookedSeats' : IDL.Nat,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'dateTime' : IDL.Int,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'eventId' : IDL.Nat,
    'bookedAt' : IDL.Int,
    'userId' : IDL.Principal,
    'quantity' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookTickets' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createEvent' : IDL.Func([Event], [IDL.Nat], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEventById' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markEventAsFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };